-- PO Cutting workflow schema
-- PostgreSQL / Supabase compatible and safe to run repeatedly.
-- The schema is quoted to preserve the requested mixed-case name.

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS "PO_Cutting";

CREATE TABLE IF NOT EXISTS "PO_Cutting".processing_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    status TEXT NOT NULL DEFAULT 'processing'
        CHECK (status IN ('processing', 'completed', 'completed_with_issues', 'failed')),
    customer TEXT,
    brand TEXT,
    season TEXT,
    source_filename TEXT NOT NULL,
    product_filename TEXT,
    llm_provider TEXT,
    llm_model TEXT,
    header_row INTEGER CHECK (header_row IS NULL OR header_row > 0),
    header_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
    input_row_count INTEGER NOT NULL DEFAULT 0 CHECK (input_row_count >= 0),
    matched_row_count INTEGER NOT NULL DEFAULT 0 CHECK (matched_row_count >= 0),
    issue_count INTEGER NOT NULL DEFAULT 0 CHECK (issue_count >= 0),
    total_quantity NUMERIC(18, 4) NOT NULL DEFAULT 0,
    error_message TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".source_files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES "PO_Cutting".processing_runs(id) ON DELETE CASCADE,
    file_role TEXT NOT NULL CHECK (file_role IN ('buy_file', 'product_export')),
    filename TEXT NOT NULL,
    sheet_name TEXT,
    file_size_bytes BIGINT CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    file_sha256 TEXT,
    headers JSONB NOT NULL DEFAULT '[]'::jsonb,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".header_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_field TEXT NOT NULL CHECK (
        canonical_field IN (
            'buyer_style_number', 'buyer_style_name', 'sku', 'product_description',
            'color', 'color_code', 'size', 'quantity', 'delivery_date', 'season',
            'customer', 'factory', 'currency', 'unit_cost', 'po_number'
        )
    ),
    source_header TEXT NOT NULL,
    normalized_header TEXT NOT NULL,
    brand TEXT NOT NULL DEFAULT '*',
    priority INTEGER NOT NULL DEFAULT 100,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (canonical_field, normalized_header, brand)
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".buy_file_rows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES "PO_Cutting".processing_runs(id) ON DELETE CASCADE,
    source_file_id UUID REFERENCES "PO_Cutting".source_files(id) ON DELETE SET NULL,
    source_sheet TEXT NOT NULL,
    source_row INTEGER NOT NULL CHECK (source_row > 0),
    po_number TEXT,
    buyer_style_number TEXT,
    buyer_style_name TEXT,
    sku TEXT,
    product_description TEXT,
    color TEXT,
    color_code TEXT,
    color_name TEXT,
    size_name TEXT NOT NULL DEFAULT 'One Size',
    quantity NUMERIC(18, 4),
    delivery_date DATE,
    season TEXT,
    customer TEXT,
    factory TEXT,
    currency TEXT NOT NULL DEFAULT 'USD',
    unit_cost NUMERIC(18, 6),
    raw_values JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, source_sheet, source_row)
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".nexgen_products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_file_id UUID REFERENCES "PO_Cutting".source_files(id) ON DELETE SET NULL,
    product_name TEXT,
    product_external_ref TEXT,
    color_name TEXT,
    color_code TEXT,
    size_name TEXT,
    buyer_style_number TEXT NOT NULL,
    buyer_style_name TEXT,
    cost NUMERIC(18, 6),
    sell NUMERIC(18, 6),
    costing_reference TEXT,
    customer_name TEXT,
    factory TEXT,
    normalized_style TEXT NOT NULL,
    normalized_color_code TEXT,
    normalized_size TEXT,
    raw_values JSONB NOT NULL DEFAULT '{}'::jsonb,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".match_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES "PO_Cutting".processing_runs(id) ON DELETE CASCADE,
    buy_file_row_id UUID NOT NULL REFERENCES "PO_Cutting".buy_file_rows(id) ON DELETE CASCADE,
    nexgen_product_id UUID REFERENCES "PO_Cutting".nexgen_products(id) ON DELETE SET NULL,
    match_status TEXT NOT NULL
        CHECK (match_status IN ('matched', 'ambiguous', 'unmatched', 'manual')),
    match_method TEXT,
    match_score NUMERIC(5, 2) CHECK (match_score IS NULL OR match_score BETWEEN 0 AND 100),
    matched_style TEXT,
    matched_color_code TEXT,
    matched_size TEXT,
    matched_sell NUMERIC(18, 6),
    notes TEXT,
    candidates JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, buy_file_row_id)
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES "PO_Cutting".processing_runs(id) ON DELETE CASCADE,
    purchase_order TEXT NOT NULL,
    product_supplier TEXT,
    status TEXT NOT NULL DEFAULT 'Confirmed',
    customer TEXT,
    transport_method TEXT,
    transport_location TEXT,
    payment_term TEXT,
    template TEXT,
    key_date DATE,
    closed_date DATE,
    default_delivery_date DATE,
    comments TEXT,
    currency TEXT NOT NULL DEFAULT 'USD',
    key_user1 TEXT,
    key_user2 TEXT,
    key_user3 TEXT,
    key_user4 TEXT,
    key_user5 TEXT,
    key_user6 TEXT,
    key_user7 TEXT,
    key_user8 TEXT,
    archive_date DATE,
    purchase_uom TEXT NOT NULL DEFAULT 'PCS',
    selling_uom TEXT NOT NULL DEFAULT 'PCS',
    product_supplier_ext TEXT,
    find_field_product_supplier TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, purchase_order)
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".order_lines (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES "PO_Cutting".processing_runs(id) ON DELETE CASCADE,
    order_id UUID NOT NULL REFERENCES "PO_Cutting".orders(id) ON DELETE CASCADE,
    line_item INTEGER NOT NULL CHECK (line_item > 0),
    product_range TEXT,
    product TEXT,
    customer TEXT,
    delivery_date DATE,
    transport_method TEXT,
    transport_location TEXT,
    status TEXT NOT NULL DEFAULT 'Confirmed',
    purchase_price NUMERIC(18, 6),
    selling_price NUMERIC(18, 6),
    template TEXT,
    key_date DATE,
    supplier_profile TEXT,
    closed_date DATE,
    comments TEXT,
    currency TEXT NOT NULL DEFAULT 'USD',
    archive_date DATE,
    product_external_ref TEXT,
    product_customer_ref TEXT,
    purchase_uom TEXT NOT NULL DEFAULT 'PCS',
    selling_uom TEXT NOT NULL DEFAULT 'PCS',
    udf_buyer_po_number TEXT,
    udf_start_date DATE,
    udf_canel_date DATE,
    udf_inspection_result TEXT,
    udf_report_type TEXT,
    udf_inspector TEXT,
    udf_approval_status TEXT,
    udf_submitted_inspection_date DATE,
    find_field_product TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (order_id, line_item)
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".order_sizes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES "PO_Cutting".processing_runs(id) ON DELETE CASCADE,
    order_line_id UUID NOT NULL REFERENCES "PO_Cutting".order_lines(id) ON DELETE CASCADE,
    size_name TEXT NOT NULL,
    product_size TEXT NOT NULL,
    quantity NUMERIC(18, 4) NOT NULL CHECK (quantity >= 0),
    range_name TEXT,
    product TEXT,
    colour TEXT,
    customer TEXT,
    department TEXT,
    custom_attribute1 TEXT,
    custom_attribute2 TEXT,
    custom_attribute3 TEXT,
    line_ratio TEXT,
    colour_ext TEXT,
    customer_ext TEXT,
    department_ext TEXT,
    custom_attribute1_ext TEXT,
    custom_attribute2_ext TEXT,
    custom_attribute3_ext TEXT,
    product_external_ref TEXT,
    product_customer_ref TEXT,
    find_field_colour TEXT,
    find_field_customer TEXT,
    find_field_department TEXT,
    find_field_custom_attribute1 TEXT,
    find_field_custom_attribute2 TEXT,
    find_field_custom_attribute3 TEXT,
    find_field_product TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (order_line_id, size_name, product_size)
);

CREATE TABLE IF NOT EXISTS "PO_Cutting".validation_issues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id UUID NOT NULL REFERENCES "PO_Cutting".processing_runs(id) ON DELETE CASCADE,
    buy_file_row_id UUID REFERENCES "PO_Cutting".buy_file_rows(id) ON DELETE CASCADE,
    severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'error')),
    issue_code TEXT NOT NULL,
    field_name TEXT,
    message TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_po_cutting_runs_created
    ON "PO_Cutting".processing_runs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_po_cutting_buy_rows_run
    ON "PO_Cutting".buy_file_rows (run_id);
CREATE INDEX IF NOT EXISTS idx_po_cutting_buy_rows_match
    ON "PO_Cutting".buy_file_rows (buyer_style_number, color_code, size_name);
CREATE INDEX IF NOT EXISTS idx_po_cutting_products_match
    ON "PO_Cutting".nexgen_products (normalized_style, normalized_color_code, normalized_size);
CREATE INDEX IF NOT EXISTS idx_po_cutting_products_sell
    ON "PO_Cutting".nexgen_products (sell);
CREATE INDEX IF NOT EXISTS idx_po_cutting_match_status
    ON "PO_Cutting".match_results (run_id, match_status);
CREATE INDEX IF NOT EXISTS idx_po_cutting_orders_run
    ON "PO_Cutting".orders (run_id);
CREATE INDEX IF NOT EXISTS idx_po_cutting_lines_order
    ON "PO_Cutting".order_lines (order_id);
CREATE INDEX IF NOT EXISTS idx_po_cutting_sizes_line
    ON "PO_Cutting".order_sizes (order_line_id);
CREATE INDEX IF NOT EXISTS idx_po_cutting_issues_run
    ON "PO_Cutting".validation_issues (run_id, severity);

-- Existing application header aliases plus the TNF sample headers.
INSERT INTO "PO_Cutting".header_aliases
    (canonical_field, source_header, normalized_header, brand, priority)
VALUES
    ('po_number', 'FINAL PO CUT #', 'final po cut', 'TNF', 10),
    ('po_number', 'MASTER PO#', 'master po', '*', 20),
    ('po_number', 'PO Number', 'po number', '*', 50),
    ('po_number', 'Purchase Order', 'purchase order', '*', 50),
    ('buyer_style_number', 'STYLE#', 'style', 'TNF', 10),
    ('buyer_style_number', 'Style Number', 'style number', '*', 50),
    ('buyer_style_number', 'Buyer Style Number', 'buyer style number', '*', 50),
    ('buyer_style_number', 'Article', 'article', '*', 50),
    ('buyer_style_name', 'STYLE NAME', 'style name', '*', 20),
    ('sku', 'MATERIAL', 'material', 'TNF', 10),
    ('sku', 'SKU', 'sku', '*', 50),
    ('sku', 'Product Code', 'product code', '*', 50),
    ('product_description', 'MATERIAL DESCRIPTION SHORT', 'material description short', 'TNF', 10),
    ('product_description', 'LONGTEXT', 'longtext', '*', 20),
    ('product_description', 'Product Description', 'product description', '*', 50),
    ('color', 'COLORWAY NAME', 'colorway name', 'TNF', 10),
    ('color', 'Color Name', 'color name', '*', 50),
    ('color', 'Colour Name', 'colour name', '*', 50),
    ('color_code', 'STYLE COLOR', 'style color', 'TNF', 10),
    ('color_code', 'Color Code', 'color code', '*', 50),
    ('color_code', 'Colour Code', 'colour code', '*', 50),
    ('size', 'SIZE 1', 'size 1', 'TNF', 10),
    ('size', 'Size Name', 'size name', '*', 50),
    ('size', 'Product Size', 'product size', '*', 50),
    ('quantity', 'TOTAL QUANTITY', 'total quantity', 'TNF', 10),
    ('quantity', 'Order Qty', 'order qty', '*', 50),
    ('quantity', 'Quantity', 'quantity', '*', 50),
    ('delivery_date', 'VENDOR CONFIRMED CRD', 'vendor confirmed crd', 'TNF', 10),
    ('delivery_date', 'Delivery Date', 'delivery date', '*', 50),
    ('delivery_date', 'Ex Factory', 'ex factory', '*', 50),
    ('season', 'SEASON', 'season', '*', 20),
    ('customer', 'SOLD-TO PARTY', 'sold to party', 'TNF', 10),
    ('customer', 'Customer', 'customer', '*', 50),
    ('factory', 'FINAL FACTORY NAME', 'final factory name', 'TNF', 10),
    ('factory', 'Factory', 'factory', '*', 50),
    ('factory', 'Vendor', 'vendor', '*', 50),
    ('currency', 'FINAL CURRENCY', 'final currency', 'TNF', 10),
    ('currency', 'Currency', 'currency', '*', 50),
    ('unit_cost', 'FOB', 'fob', 'TNF', 10),
    ('unit_cost', 'Unit Cost', 'unit cost', '*', 50),
    ('unit_cost', 'Unit Price', 'unit price', '*', 50)
ON CONFLICT (canonical_field, normalized_header, brand)
DO UPDATE SET
    source_header = EXCLUDED.source_header,
    priority = EXCLUDED.priority,
    is_active = true,
    updated_at = now();

-- Export views retain the exact headers currently generated by the application.
CREATE OR REPLACE VIEW "PO_Cutting".orders_export AS
SELECT
    o.run_id AS "RunId",
    o.purchase_order AS "PurchaseOrder",
    o.product_supplier AS "ProductSupplier",
    o.status AS "Status",
    o.customer AS "Customer",
    o.transport_method AS "TransportMethod",
    o.transport_location AS "TransportLocation",
    o.payment_term AS "PaymentTerm",
    o.template AS "Template",
    o.key_date AS "KeyDate",
    o.closed_date AS "ClosedDate",
    o.default_delivery_date AS "DefaultDeliveryDate",
    o.comments AS "Comments",
    o.currency AS "Currency",
    o.key_user1 AS "KeyUser1",
    o.key_user2 AS "KeyUser2",
    o.key_user3 AS "KeyUser3",
    o.key_user4 AS "KeyUser4",
    o.key_user5 AS "KeyUser5",
    o.key_user6 AS "KeyUser6",
    o.key_user7 AS "KeyUser7",
    o.key_user8 AS "KeyUser8",
    o.archive_date AS "ArchiveDate",
    o.purchase_uom AS "PurchaseUOM",
    o.selling_uom AS "SellingUOM",
    o.product_supplier_ext AS "ProductSupplierExt",
    o.find_field_product_supplier AS "FindField_ProductSupplier"
FROM "PO_Cutting".orders o;

CREATE OR REPLACE VIEW "PO_Cutting".lines_export AS
SELECT
    l.run_id AS "RunId",
    o.purchase_order AS "PurchaseOrder",
    l.line_item AS "LineItem",
    l.product_range AS "ProductRange",
    l.product AS "Product",
    l.customer AS "Customer",
    l.delivery_date AS "DeliveryDate",
    l.transport_method AS "TransportMethod",
    l.transport_location AS "TransportLocation",
    l.status AS "Status",
    l.purchase_price AS "PurchasePrice",
    l.selling_price AS "SellingPrice",
    l.template AS "Template",
    l.key_date AS "KeyDate",
    l.supplier_profile AS "SupplierProfile",
    l.closed_date AS "ClosedDate",
    l.comments AS "Comments",
    l.currency AS "Currency",
    l.archive_date AS "ArchiveDate",
    l.product_external_ref AS "ProductExternalRef",
    l.product_customer_ref AS "ProductCustomerRef",
    l.purchase_uom AS "PurchaseUOM",
    l.selling_uom AS "SellingUOM",
    l.udf_buyer_po_number AS "UDF-buyer_po_number",
    l.udf_start_date AS "UDF-start_date",
    l.udf_canel_date AS "UDF-canel_date",
    l.udf_inspection_result AS "UDF-Inspection result",
    l.udf_report_type AS "UDF-Report Type",
    l.udf_inspector AS "UDF-Inspector",
    l.udf_approval_status AS "UDF-Approval Status",
    l.udf_submitted_inspection_date AS "UDF-Submitted inspection date",
    l.find_field_product AS "FindField_Product"
FROM "PO_Cutting".order_lines l
JOIN "PO_Cutting".orders o ON o.id = l.order_id;

CREATE OR REPLACE VIEW "PO_Cutting".order_sizes_export AS
SELECT
    s.run_id AS "RunId",
    o.purchase_order AS "PurchaseOrder",
    l.line_item AS "LineItem",
    s.range_name AS "Range",
    s.product AS "Product",
    s.size_name AS "SizeName",
    s.product_size AS "ProductSize",
    s.quantity AS "Quantity",
    s.colour AS "Colour",
    s.customer AS "Customer",
    s.department AS "Department",
    s.custom_attribute1 AS "CustomAttribute1",
    s.custom_attribute2 AS "CustomAttribute2",
    s.custom_attribute3 AS "CustomAttribute3",
    s.line_ratio AS "LineRatio",
    s.colour_ext AS "ColourExt",
    s.customer_ext AS "CustomerExt",
    s.department_ext AS "DepartmentExt",
    s.custom_attribute1_ext AS "CustomAttribute1Ext",
    s.custom_attribute2_ext AS "CustomAttribute2Ext",
    s.custom_attribute3_ext AS "CustomAttribute3Ext",
    s.product_external_ref AS "ProductExternalRef",
    s.product_customer_ref AS "ProductCustomerRef",
    s.find_field_colour AS "FindField_Colour",
    s.find_field_customer AS "FindField_Customer",
    s.find_field_department AS "FindField_Department",
    s.find_field_custom_attribute1 AS "FindField_CustomAttribute1",
    s.find_field_custom_attribute2 AS "FindField_CustomAttribute2",
    s.find_field_custom_attribute3 AS "FindField_CustomAttribute3",
    s.find_field_product AS "FindField_Product"
FROM "PO_Cutting".order_sizes s
JOIN "PO_Cutting".order_lines l ON l.id = s.order_line_id
JOIN "PO_Cutting".orders o ON o.id = l.order_id;

COMMENT ON SCHEMA "PO_Cutting" IS
    'PO Cutting buy-file extraction, Nexgen product matching, validation, and Excel output data.';
